"""
Notification Agent for Predictive Maintenance.

Detects HIGH-RISK / HIGH-PRIORITY alerts generated by the predictive-maintenance
pipeline, prevents duplicate notifications for the same alert event, composes
detailed email notifications with attached CSV records, and sends emails via SMTP.

Features:
- Reuses existing prediction, confidence, SHAP explainability, and AI insights.
- Thread-safe deduplication and notification history tracking.
- Non-blocking asynchronous dispatching via background ThreadPoolExecutor.
- Zero external dependencies: uses Python standard libraries (smtplib, email.message).
- Graceful error handling: failures never crash the prediction or dashboard pipeline.
"""

import os
import sys
import io
import csv
import re
import smtplib
import threading
import concurrent.futures
from email.message import EmailMessage
from typing import Optional, Dict, Any, Tuple, List

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

# Global thread-safe state tracking
_NOTIFIED_EVENTS: set[str] = set()
_NOTIFICATION_HISTORY: List[Dict[str, Any]] = []
_STATE_LOCK = threading.Lock()
_NOTIFICATION_EXECUTOR = concurrent.futures.ThreadPoolExecutor(
    max_workers=4,
    thread_name_prefix="notification_agent"
)


def reset_notification_state() -> None:
    """
    Resets in-memory notification state tracking (useful for testing or application reset).
    """
    with _STATE_LOCK:
        _NOTIFIED_EVENTS.clear()
        _NOTIFICATION_HISTORY.clear()


def is_high_risk(diagnosis: dict, recommendation: Optional[dict] = None) -> bool:
    """
    Determines whether an alert represents a HIGH-RISK condition based on the
    existing project's risk logic:
    - prediction == 1 AND confidence >= 0.70 (or 70%)
    - OR recommendation urgency == "High"
    """
    if not diagnosis:
        return False

    pred = diagnosis.get("prediction")
    try:
        pred_val = int(pred) if pred is not None else 0
    except (ValueError, TypeError):
        pred_val = 0

    conf = diagnosis.get("confidence", 0.0)
    try:
        conf_val = float(conf) if conf is not None else 0.0
    except (ValueError, TypeError):
        conf_val = 0.0

    # Handle confidence formatted as percentage or 0.0-1.0
    if conf_val > 1.0:
        conf_val = conf_val / 100.0

    urgency = ""
    if recommendation and isinstance(recommendation, dict):
        urgency = str(recommendation.get("urgency", "")).strip().lower()

    # Existing project definition of high risk
    if urgency == "high":
        return True
    if pred_val == 1 and conf_val >= 0.70:
        return True

    return False


def make_notification_event_key(
    machine_id: str,
    timestamp: str,
    diagnosis: dict,
    recommendation: Optional[dict] = None
) -> str:
    """
    Constructs a stable, deterministic event key for deduplication.
    Prevents repeated emails when Streamlit refreshes or re-renders.
    """
    pred = diagnosis.get("prediction", "")
    conf = diagnosis.get("confidence", "")
    urgency = recommendation.get("urgency", "") if recommendation else ""
    return f"{machine_id}|{timestamp}|pred:{pred}|conf:{conf}|urgency:{urgency}"


def has_been_notified(event_key: str) -> bool:
    """
    Checks if a notification has already been sent/recorded for this event key.
    """
    with _STATE_LOCK:
        return event_key in _NOTIFIED_EVENTS


def mark_notified(event_key: str, record_summary: Optional[Dict[str, Any]] = None) -> None:
    """
    Marks an event key as notified and stores a summary in history.
    """
    with _STATE_LOCK:
        _NOTIFIED_EVENTS.add(event_key)
        if record_summary:
            _NOTIFICATION_HISTORY.append(record_summary)
            # Keep history bounded
            if len(_NOTIFICATION_HISTORY) > 200:
                _NOTIFICATION_HISTORY.pop(0)


def get_last_notification_status() -> Optional[Dict[str, Any]]:
    """
    Returns the most recent notification record or None.
    """
    with _STATE_LOCK:
        if _NOTIFICATION_HISTORY:
            return dict(_NOTIFICATION_HISTORY[-1])
        return None


def get_notification_history() -> List[Dict[str, Any]]:
    """
    Returns a copy of the notification history.
    """
    with _STATE_LOCK:
        return [dict(item) for item in _NOTIFICATION_HISTORY]


def _format_confidence(conf_val: Any) -> str:
    """Helper to format confidence value cleanly as percentage string."""
    try:
        c = float(conf_val)
        if c <= 1.0:
            return f"{c:.0%}"
        return f"{c:.0f}%"
    except (ValueError, TypeError):
        return str(conf_val)


def generate_alert_csv(record: Dict[str, Any]) -> Tuple[bytes, str]:
    """
    Generates an in-memory CSV file containing the alert and telemetry record.
    Returns (csv_bytes, filename).
    """
    machine_id = str(record.get("machine_id", "Machine-001"))
    timestamp = str(record.get("timestamp", "N/A"))
    diagnosis = record.get("diagnosis", {}) or {}
    recommendation = record.get("recommendation", {}) or {}
    ai_insight = record.get("ai_insight", "")
    sensor_data = record.get("sensor_data", {}) or {}

    pred = diagnosis.get("prediction", 0)
    pred_str = "Failure" if pred == 1 else "Normal"
    conf_str = _format_confidence(diagnosis.get("confidence", 0.0))
    urgency = recommendation.get("urgency", "High")
    action = recommendation.get("action", "Schedule immediate maintenance")
    shap_reason = diagnosis.get("plain_explanation") or diagnosis.get("explanation", "")

    csv_data = {
        "Timestamp": timestamp,
        "Machine_ID": machine_id,
        "Prediction": pred_str,
        "Confidence": conf_str,
        "Risk_Level": urgency,
        "Recommended_Action": action,
        "SHAP_Reason": shap_reason,
        "AI_Insight": ai_insight,
    }

    # Add sensor telemetry fields if available
    for key in [
        "Type",
        "Air temperature [K]",
        "Process temperature [K]",
        "Rotational speed [rpm]",
        "Torque [Nm]",
        "Tool wear [min]",
    ]:
        if key in sensor_data:
            csv_data[key] = sensor_data[key]

    output = io.StringIO()
    writer = csv.DictWriter(output, fieldnames=list(csv_data.keys()))
    writer.writeheader()
    writer.writerow(csv_data)

    clean_id = re.sub(r'[^a-zA-Z0-9_\-]', '_', machine_id)
    clean_time = re.sub(r'[^a-zA-Z0-9_\-]', '_', timestamp)
    filename = f"high_risk_alert_{clean_id}_{clean_time}.csv"


    return output.getvalue().encode("utf-8"), filename


def generate_email_content(record: Dict[str, Any]) -> Tuple[str, str]:
    """
    Generates subject and plain-text body for the notification email.
    Reuses existing SHAP explanation, AI insight, and recommendation.
    """
    machine_id = str(record.get("machine_id", "Machine-001"))
    timestamp = str(record.get("timestamp", "N/A"))
    diagnosis = record.get("diagnosis", {}) or {}
    recommendation = record.get("recommendation", {}) or {}
    ai_insight = record.get("ai_insight", "").strip()
    sensor_data = record.get("sensor_data", {}) or {}

    pred = diagnosis.get("prediction", 1)
    pred_text = "Failure likely" if pred == 1 else "Normal operation"
    conf_text = _format_confidence(diagnosis.get("confidence", 0.0))
    urgency = recommendation.get("urgency", "High")
    action = recommendation.get("action", "Schedule immediate maintenance")
    shap_reason = (
        diagnosis.get("plain_explanation")
        or diagnosis.get("explanation", "")
        or "Elevated operating parameters detected."
    )

    if not ai_insight:
        ai_insight = (
            f"Automated risk detection identified high failure probability ({conf_text}). "
            f"Prioritize inspection and {action.lower()} before continued operation causes machine failure."
        )

    # Format sensor section if available
    sensor_lines = []
    if sensor_data:
        sensor_lines.append("Sensor Telemetry:")
        for k, v in sensor_data.items():
            sensor_lines.append(f"  - {k}: {v}")
        sensor_block = "\n".join(sensor_lines) + "\n\n"
    else:
        sensor_block = ""

    subject = f"[HIGH ALERT] Predictive Maintenance Alert - Machine {machine_id}"

    body = f"""HIGH-RISK MAINTENANCE ALERT
==================================================
Machine: {machine_id}
Time: {timestamp}
Risk: {urgency.upper() if urgency else 'HIGH'}
Prediction: {pred_text}
Confidence: {conf_text}

Reason:
{shap_reason}

AI Insight:
{ai_insight}

Recommended Action:
{action}

{sensor_block}==================================================
A CSV file containing the relevant alert/data record is attached.
"""
    return subject, body


def send_notification_email(
    subject: str,
    body: str,
    csv_bytes: Optional[bytes] = None,
    csv_filename: str = "high_risk_alert.csv",
    to_email: Optional[str] = None
) -> Dict[str, Any]:
    """
    Sends notification email via standard SMTP.
    Safely catches all connection, authentication, and transmission errors.
    Returns status dict: {"success": bool, "status": "sent"|"skipped"|"failed", "reason"/"error": ...}
    """
    smtp_host = os.environ.get("SMTP_HOST", "").strip()
    smtp_port_raw = os.environ.get("SMTP_PORT", "587").strip()
    recipient = to_email or os.environ.get("NOTIFICATION_EMAIL_TO", "").strip()
    sender = (
        os.environ.get("NOTIFICATION_EMAIL_FROM", "").strip()
        or os.environ.get("SMTP_USERNAME", "").strip()
        or "alerts@predictive-maintenance.local"
    )
    username = os.environ.get("SMTP_USERNAME", "").strip()
    password = os.environ.get("SMTP_PASSWORD", "").strip()

    # Graceful fallback if SMTP configuration is missing
    if not smtp_host or not recipient:
        print("[NOTIFY] Notification skipped: SMTP configuration missing (SMTP_HOST or NOTIFICATION_EMAIL_TO not set)")
        return {
            "success": False,
            "status": "skipped",
            "reason": "missing_config",
            "recipient": recipient or "None",
            "host": smtp_host or "None"
        }

    try:
        smtp_port = int(smtp_port_raw)
    except ValueError:
        smtp_port = 587

    # Build message
    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = recipient
    msg.set_content(body)

    if csv_bytes:
        msg.add_attachment(
            csv_bytes,
            maintype="text",
            subtype="csv",
            filename=csv_filename
        )

    timeout = float(os.environ.get("SMTP_TIMEOUT", "10.0"))

    try:
        if smtp_port == 465:
            # Direct SSL
            server = smtplib.SMTP_SSL(smtp_host, smtp_port, timeout=timeout)
            server.ehlo()
        else:
            # STARTTLS standard (587, 25, etc.)
            server = smtplib.SMTP(smtp_host, smtp_port, timeout=timeout)
            server.ehlo()
            try:
                server.starttls()
                server.ehlo()
            except smtplib.SMTPException:
                pass  # Server might not support TLS in test/local environments

        if username and password:
            server.login(username, password)

        server.send_message(msg)
        server.quit()

        print(f"[NOTIFY] Email sent successfully to {recipient}")
        return {
            "success": True,
            "status": "sent",
            "recipient": recipient,
            "subject": subject
        }

    except Exception as e:
        err_msg = str(e)
        print(f"[WARN] Notification email failed: {err_msg}")
        return {
            "success": False,
            "status": "failed",
            "error": err_msg,
            "recipient": recipient
        }


def notification_agent(
    record: Dict[str, Any],
    async_send: bool = False
) -> Dict[str, Any]:
    """
    Main entrypoint for Notification Agent.

    Parameters:
    - record: dict containing:
        - machine_id (optional, str)
        - timestamp (optional, str or int)
        - diagnosis (dict from diagnosis_agent)
        - recommendation (dict from recommendation_agent)
        - ai_insight (optional str, existing AI insight)
        - sensor_data (optional dict, sensor telemetry row)
    - async_send: if True, dispatches SMTP sending to background thread pool.

    Returns:
    - Dict with execution summary. NEVER raises unhandled exceptions.
    """
    try:
        diagnosis = record.get("diagnosis", {}) or {}
        recommendation = record.get("recommendation", {}) or {}
        machine_id = str(record.get("machine_id", "Machine-001"))
        timestamp = str(record.get("timestamp", "N/A"))

        # Step 1: Detect High-Risk
        if not is_high_risk(diagnosis, recommendation):
            return {
                "is_high_risk": False,
                "notified": False,
                "status": "ignored",
                "reason": "not_high_risk"
            }

        # Step 2: Prevent Duplicates
        event_key = make_notification_event_key(machine_id, timestamp, diagnosis, recommendation)
        if has_been_notified(event_key):
            print(f"[NOTIFY] Duplicate alert skipped: {event_key}")
            return {
                "is_high_risk": True,
                "notified": False,
                "status": "skipped",
                "reason": "duplicate",
                "event_key": event_key
            }

        conf_str = _format_confidence(diagnosis.get("confidence", 0.0))
        print(f"[NOTIFY] High-risk alert detected for {machine_id} (Time: {timestamp}, Confidence: {conf_str})")

        # Step 3: Generate Email Content & CSV Attachment
        subject, body = generate_email_content(record)
        csv_bytes, csv_filename = generate_alert_csv(record)

        summary_entry = {
            "machine_id": machine_id,
            "timestamp": timestamp,
            "event_key": event_key,
            "subject": subject,
            "confidence": conf_str,
            "recipient": os.environ.get("NOTIFICATION_EMAIL_TO", "N/A"),
            "status": "pending"
        }

        # Step 4: Dispatch Email
        if async_send:
            def _async_worker():
                res = send_notification_email(
                    subject=subject,
                    body=body,
                    csv_bytes=csv_bytes,
                    csv_filename=csv_filename
                )
                summary_entry["status"] = res.get("status", "unknown")
                summary_entry["error"] = res.get("error")
                mark_notified(event_key, summary_entry)

            _NOTIFICATION_EXECUTOR.submit(_async_worker)
            return {
                "is_high_risk": True,
                "notified": True,
                "status": "dispatched_async",
                "event_key": event_key,
                "subject": subject,
                "csv_filename": csv_filename
            }
        else:
            res = send_notification_email(
                subject=subject,
                body=body,
                csv_bytes=csv_bytes,
                csv_filename=csv_filename
            )
            summary_entry["status"] = res.get("status", "unknown")
            summary_entry["error"] = res.get("error")
            mark_notified(event_key, summary_entry)

            return {
                "is_high_risk": True,
                "notified": res.get("success", False),
                "status": res.get("status", "unknown"),
                "error": res.get("error"),
                "event_key": event_key,
                "subject": subject,
                "csv_filename": csv_filename
            }

    except Exception as e:
        err_msg = str(e)
        print(f"[WARN] Notification agent encountered error: {err_msg}")
        return {
            "is_high_risk": False,
            "notified": False,
            "status": "failed",
            "error": err_msg
        }


# Quick manual test
if __name__ == "__main__":
    sample_record = {
        "machine_id": "Machine-M01",
        "timestamp": "t=42",
        "diagnosis": {
            "prediction": 1,
            "confidence": 0.88,
            "explanation": "Torque [Nm] increased failure risk; Tool wear [min] increased failure risk",
            "plain_explanation": "Torque [Nm] increased failure risk; Tool wear [min] increased failure risk"
        },
        "recommendation": {
            "action": "Schedule immediate maintenance",
            "urgency": "High",
            "confidence": 0.88
        },
        "ai_insight": "Critical torque and tool wear detected. Schedule immediate maintenance.",
        "sensor_data": {
            "Type": "M",
            "Air temperature [K]": 300.2,
            "Process temperature [K]": 310.5,
            "Rotational speed [rpm]": 1380,
            "Torque [Nm]": 62.4,
            "Tool wear [min]": 215
        }
    }

    print("High risk check:", is_high_risk(sample_record["diagnosis"], sample_record["recommendation"]))
    print("Event key:", make_notification_event_key(sample_record["machine_id"], sample_record["timestamp"], sample_record["diagnosis"], sample_record["recommendation"]))
    res = notification_agent(sample_record, async_send=False)
    print("Notification result (missing config expected):", res)
